endpoints = {
    "public_info_url": "/api/info/public",
    "status_url": "/status.cgi",
    "fw_url": "/api/firewall/user-rules",
    "pfw_url": "/api/firewall/port-forward",
    "pppinfo_url": "/api/pppoe/info",
    "ppprestart_url": "/api/pppoe/restart",
    "arp_url": "/arp.cgi",
    "routes_url": "/sroutes.cgi",
    "brmacs_url": "/brmacs.cgi",
    "leases_url": "/api/dhcp-server/leases",
    "readCfgUrl": "/getcfg.cgi",
    "writeCfgUrl": "/writecfg.cgi",
    "writePartialCfgUrl": "/api/cfg",
    "regdomain_url": "/api/regdomain",
    "siteSurveyUrl": "/survey.json.cgi",
    "dhcpc_info_url": "/api/dhcp-client/info",
    "dhcpc_renew_url": "/api/dhcp-client/renew",
    "dhcpc_release_url": "/api/dhcp-client/release",
    "discovery_url": "/discovery.cgi",
    "poll_url": "/poll.cgi",
    "ping_url": "/pingtest_action.cgi",
    "traceroute_url": "/api/traceroute",
    "speed_test_url": "/sptest_action.cgi",
    "ipscan_url": "/ipscan.cgi",
    "warnings_url": "/api/warnings",
    "warnings_dismiss_url": "/api/warnings/dismiss",
    "fwflash_url": "/fwflash.cgi",
    "reboot_url": "/reboot.cgi",
    "reset_url": "/reset.cgi",
    "pwd_url": "/pwd.cgi",
    "apply_url": "/apply.cgi",
    "unlock_unii_url": "/api/regdomain/activate-unii",
    "discard_url": "/discard.cgi",
    "ethtool_url": "/ethtool.cgi",
    "test_mode_url": "/test_mode.cgi",
    "crash_log_url": "/crashlog.cgi",
    "crash_report_url": "//airos-api.ubnt.com/crashreport/",
    "temperature_url": "/temperature.cgi",
    "sta_kick_url": "/stakick.cgi",
    "airview_data_url": "/airviewdata.cgi",
    "logout_url": "/logout.cgi",
    "airmagic_data_url": "/amdata.cgi",
    "log_url": "/api/logs",
    "log_clear_url": "/api/logs/clear",
    "help_url": "/api/info/help",
    "statusReloadInterval": 1e3,
    "graphsInterval": 1100,
    "graphsTickCount": 120,
    "softRestartTime": 1e5,
    "rssi_max": 36,
    "atpc_rssi_min": 26,
    "atpc_rssi_default": 36,
    "atpc_rssi_max": 46,
    "sectionSlideDuration": 300,
    "alertContainerSelector": "#alert_container",
    "failureCountBeforeBlock": 3,
    "failureCountBigProblem": 80,
    "min_mtu": 68,
    "min_mtu_ipv6": 1280,
    "default_mtu": 1500,
    "default_max_mtu": 1524,
    "default_ath_max_mtu": 2024,
    "max_sshd_auth_keys": 10,
    "defaultUrl": "http://192.168.1.20/",
    "indexUrl": "/",
    "websocketReconnectTimeout": 3e3,
    "defaultPassword": "ubnt",
    "defaultUserName": "ubnt",
    "provmode_ctrl_url": "/api/provmode",
    "airLink_url": "https://link.ui.com",
    "auth_url": "/api/auth",
    "ticket_url": "api/auth-ticket",
    "min_power": -95,
    "signal_to_rate_map": [-120, -95, -90, -83, -69],
    "rate_colors": ["200,89,36", "218,180,43", "123,194,66", "69,192,163", "33,142,209"],
    "signal_to_rate_map_m": [-120, -95, -90, -83],
    "rate_colors_m": ["200,89,36", "218,180,43", "123,194,66", "69,192,163"],
    "signal_to_rate_map_ad": [-120, -63, -55],
    "rate_colors_ad": ["218,180,43", "123,194,66", "33,142,209"],
    "unms_enable_url": "/api/unms/enable",
    "unms_disable_url": "/api/unms/disable",
    "countries_url": "/api/regdomain/countries",
    "set_country_url": "/api/regdomain/country",
    "call_home_url": "/api/ch",
    "call_home_dismiss_url": "/api/ch/dismiss",
    "call_home_server_url": "https://dev.ubnt.com/update/v1"
}